#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
