#!/usr/bin/env bash
#redirecting to a different location
apt-get update
apt-get install -y nginx
sudo sed -i "listen 80 default_server/a rewrite 301 ^redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-available/default
sudo service nginx restart
