#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# displays only username, userid, homedirectory
while read passwd; do
      echo "$passwd" | cut -d: -f1,3,6
done < /etc/passwd
