#!/usr/env bash
# local host: 127.0.0.2
# facebook : 8.8.8.8
# change the following ip address to the specified above

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8 		facebook,com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
